name       : haskell-rfc5051
version    : 0.1.0.3
release    : 3
source     :
    - https://hackage.haskell.org/package/rfc5051-0.1.0.3/rfc5051-0.1.0.3.tar.gz : e38dab28a5625774be60545c8c99e647b79bbc0ac0bc9c65fe6b2ebef160642b
license    : BSD-3-Clause
component  : programming.haskell
summary    : This library implements i;unicode-casemap, the simple, non locale-sensitive
    unicode collation algorithm described in RFC 5051
description: "This library implements i;unicode-casemap, the simple, non locale-sensitive\
    \ unicode collation algorithm described in RFC 5051 \n"
builddeps  :
    - ghc
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
