name       : haskell-rfc5051
version    : 0.1.0.4
release    : 4
source     :
    - https://hackage.haskell.org/package/rfc5051-0.1.0.4/rfc5051-0.1.0.4.tar.gz : 615daa230eabc781eff1d3ce94c42fc5ba6188dbeb115a233328454b02c1b3d3
license    : BSD-3-Clause
component  : programming.haskell
summary    : This library implements i;unicode-casemap, the simple, non locale-sensitive unicode collation algorithm described in RFC 5051
description: |
    This library implements i;unicode-casemap, the simple, non locale-sensitive unicode collation algorithm described in RFC 5051
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
